#!/bin/sh

# List all the languages
#langs="`find . -name '*.po' -printf '%P ' `"
langs="`find . -name '*.po' | sort | xargs `"

# Merge ktoshiba.pot messages for each language
# (same as "cd po; make merge" if you have the Makefiles
#  generated in the same folder Makefile.in lives)
for lang in $langs
do
	lang=`basename $lang .po`
	echo $lang
	mv "$lang.po" "$lang.po.bak"
	msgmerge -o "$lang.po" "$lang.po.bak" "ktoshiba.pot" && rm "$lang.po.bak"
done
