#! /bin/sh
#
# Copyright (c) 2013 Azael Avalos <coproscefalo@gmail.com>
#
# A little script helper to toggle various objects in the kernel
#

case "$1" in
    illumination)
        echo "$2" > /sys/class/leds/toshiba::illumination/brightness
        ;;
    eco)
        echo "$2" > /sys/class/leds/toshiba::eco_mode/brightness
        ;;
    kbdmode)
        echo "$2" > /sys/devices/platform/toshiba/kbd_backlight_mode
        ;;
    touchpad)
        echo "$2" > /sys/devices/platform/toshiba/touchpad
        ;;
    protect)
        echo "1" > /sys/devices/platform/toshiba_haps/protect
        ;;
    plevel)
        echo "$2" > /sys/devices/platform/toshiba_haps/protection_level
        ;;
    *)
        echo "Usage: $0 {illumination|eco|touchpad} {0,1}"
        echo "       $0 kbdmode {1,2}"
        echo "       $0 plevel {0-3}"
        echo "       $0 protect"
        exit 1
        ;;
esac
